# Python review
Goals: 
- Recall Basic python vocab
- Practice markdown 

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in out pprograms 

ex = **NumPy**:
- Core lib
- many other libs use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage 

lets import NumPy with **standard abbreviation**


In [1]:
import numpy as np

## Variables 

**Variable**: a name we assign to a particular object in Python 
Example:

In [3]:
#Assigning small array to variable a
a = np.array([[1,1,2],[3,5,8]])

In [4]:
#Check out a
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
#Can also use 'print' function 
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** (informally speaking) is a bundle of *properties* and *actions* about something specific
Ex:

Object: DF

Properties: number of rows, names of the columns, date created

Actions.: selecting rows and cols, adding new cols 

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can use variable and object interchangeably. 